# List of Methods to Read a CSV File in Python
    Read CSV file using csv.reader
    Read CSV file using .readlines() function
    Read CSV file using Pandas
    Read CSV file using csv.DictReader

# 1.using csv.reader :
        allows you to read data from a CSV file using indexes and 
        ideal for simple CSV files
        treats each line as a list of values separated by the specified delimiter (usually a comma). 
        then iterate through the rows and access individual values using their indices
        Suitable for basic scenarios where you need minimal processing.

In [2]:
import csv

In [28]:
with open("iris.csv", "r") as csvfile:
    reader_variable = csv.reader(csvfile, delimiter=",")
    for row in reader_variable:
        print(row)

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
['5.1', '3.5', '1.4', '0.2', 'Iris-setosa']
['4.9', '3', '1.4', '0.2', 'Iris-setosa']
['4.7', '3.2', '1.3', '0.2', 'Iris-setosa']
['4.6', '3.1', '1.5', '0.2', 'Iris-setosa']
['5', '3.6', '1.4', '0.2', 'Iris-setosa']
['5.4', '3.9', '1.7', '0.4', 'Iris-setosa']
['4.6', '3.4', '1.4', '0.3', 'Iris-setosa']
['5', '3.4', '1.5', '0.2', 'Iris-setosa']
['4.4', '2.9', '1.4', '0.2', 'Iris-setosa']
['4.9', '3.1', '1.5', '0.1', 'Iris-setosa']
['5.4', '3.7', '1.5', '0.2', 'Iris-setosa']
['4.8', '3.4', '1.6', '0.2', 'Iris-setosa']
['4.8', '3', '1.4', '0.1', 'Iris-setosa']
['4.3', '3', '1.1', '0.1', 'Iris-setosa']
['5.8', '4', '1.2', '0.2', 'Iris-setosa']
['5.7', '4.4', '1.5', '0.4', 'Iris-setosa']
['5.4', '3.9', '1.3', '0.4', 'Iris-setosa']
['5.1', '3.5', '1.4', '0.3', 'Iris-setosa']
['5.7', '3.8', '1.7', '0.3', 'Iris-setosa']
['5.1', '3.8', '1.5', '0.3', 'Iris-setosa']
['5.4', '3.4', '1.7', '0.2', 'Iris-setosa']
['5.1', '3.7', '1.5', '0.4', 'Iris-setosa']
['4.6', '3.6', '1', '0.2', 'Iris-setosa']
['5.1', '3.3', '1.7', '0.5', 'Iris-setosa']
['4.8', '3.4', '1.9', '0.2', 'Iris-setosa']
['5', '3', '1.6', '0.2', 'Iris-setosa']
['5', '3.4', '1.6', '0.4', 'Iris-setosa']
['5.2', '3.5', '1.5', '0.2', 'Iris-setosa']
['5.2', '3.4', '1.4', '0.2', 'Iris-setosa']
['4.7', '3.2', '1.6', '0.2', 'Iris-setosa']
['4.8', '3.1', '1.6', '0.2', 'Iris-setosa']
['5.4', '3.4', '1.5', '0.4', 'Iris-setosa']
['5.2', '4.1', '1.5', '0.1', 'Iris-setosa']
['5.5', '4.2', '1.4', '0.2', 'Iris-setosa']
['4.9', '3.1', '1.5', '0.1', 'Iris-setosa']
['5', '3.2', '1.2', '0.2', 'Iris-setosa']
['5.5', '3.5', '1.3', '0.2', 'Iris-setosa']
['4.9', '3.1', '1.5', '0.1', 'Iris-setosa']
['4.4', '3', '1.3', '0.2', 'Iris-setosa']
['5.1', '3.4', '1.5', '0.2', 'Iris-setosa']
['5', '3.5', '1.3', '0.3', 'Iris-setosa']
['4.5', '2.3', '1.3', '0.3', 'Iris-setosa']
['4.4', '3.2', '1.3', '0.2', 'Iris-setosa']
['5', '3.5', '1.6', '0.6', 'Iris-setosa']
['5.1', '3.8', '1.9', '0.4', 'Iris-setosa']
['4.8', '3', '1.4', '0.3', 'Iris-setosa']
['5.1', '3.8', '1.6', '0.2', 'Iris-setosa']
['4.6', '3.2', '1.4', '0.2', 'Iris-setosa']
['5.3', '3.7', '1.5', '0.2', 'Iris-setosa']
['5', '3.3', '1.4', '0.2', 'Iris-setosa']
['7', '3.2', '4.7', '1.4', 'Iris-versicolor']
['6.4', '3.2', '4.5', '1.5', 'Iris-versicolor']
['6.9', '3.1', '4.9', '1.5', 'Iris-versicolor']
['5.5', '2.3', '4', '1.3', 'Iris-versicolor']
['6.5', '2.8', '4.6', '1.5', 'Iris-versicolor']
['5.7', '2.8', '4.5', '1.3', 'Iris-versicolor']
['6.3', '3.3', '4.7', '1.6', 'Iris-versicolor']
['4.9', '2.4', '3.3', '1', 'Iris-versicolor']
['6.6', '2.9', '4.6', '1.3', 'Iris-versicolor']
['5.2', '2.7', '3.9', '1.4', 'Iris-versicolor']
['5', '2', '3.5', '1', 'Iris-versicolor']
['5.9', '3', '4.2', '1.5', 'Iris-versicolor']
['6', '2.2', '4', '1', 'Iris-versicolor']
['6.1', '2.9', '4.7', '1.4', 'Iris-versicolor']
['5.6', '2.9', '3.6', '1.3', 'Iris-versicolor']
['6.7', '3.1', '4.4', '1.4', 'Iris-versicolor']
['5.6', '3', '4.5', '1.5', 'Iris-versicolor']
['5.8', '2.7', '4.1', '1', 'Iris-versicolor']
['6.2', '2.2', '4.5', '1.5', 'Iris-versicolor']
['5.6', '2.5', '3.9', '1.1', 'Iris-versicolor']
['5.9', '3.2', '4.8', '1.8', 'Iris-versicolor']
['6.1', '2.8', '4', '1.3', 'Iris-versicolor']
['6.3', '2.5', '4.9', '1.5', 'Iris-versicolor']
['6.1', '2.8', '4.7', '1.2', 'Iris-versicolor']
['6.4', '2.9', '4.3', '1.3', 'Iris-versicolor']
['6.6', '3', '4.4', '1.4', 'Iris-versicolor']
['6.8', '2.8', '4.8', '1.4', 'Iris-versicolor']
['6.7', '3', '5', '1.7', 'Iris-versicolor']
['6', '2.9', '4.5', '1.5', 'Iris-versicolor']
['5.7', '2.6', '3.5', '1', 'Iris-versicolor']
['5.5', '2.4', '3.8', '1.1', 'Iris-versicolor']
['5.5', '2.4', '3.7', '1', 'Iris-versicolor']
['5.8', '2.7', '3.9', '1.2', 'Iris-versicolor']
['6', '2.7', '5.1', '1.6', 'Iris-versicolor']
['5.4', '3', '4.5', '1.5', 'Iris-versicolor']
['6', '3.4', '4.5', '1.6', 'Iris-versicolor']
['6.7', '3.1', '4.7', '1.5', 'Iris-versicolor']
['6.3', '2.3', '4.4', '1.3', 'Iris-versicolor']
['5.6', '3', '4.1', '1.3', 'Iris-versicolor']
['5.5', '2.5', '4', '1.3', 'Iris-versicolor']
['5.5', '2.6', '4.4', '1.2', 'Iris-versicolor']
['6.1', '3', '4.6', '1.4', 'Iris-versicolor']
['5.8', '2.6', '4', '1.2', 'Iris-versicolor']
['5', '2.3', '3.3', '1', 'Iris-versicolor']
['5.6', '2.7', '4.2', '1.3', 'Iris-versicolor']
['5.7', '3', '4.2', '1.2', 'Iris-versicolor']
['5.7', '2.9', '4.2', '1.3', 'Iris-versicolor']
['6.2', '2.9', '4.3', '1.3', 'Iris-versicolor']
['5.1', '2.5', '3', '1.1', 'Iris-versicolor']
['5.7', '2.8', '4.1', '1.3', 'Iris-versicolor']
['6.3', '3.3', '6', '2.5', 'Iris-virginica']
['5.8', '2.7', '5.1', '1.9', 'Iris-virginica']
['7.1', '3', '5.9', '2.1', 'Iris-virginica']
['6.3', '2.9', '5.6', '1.8', 'Iris-virginica']
['6.5', '3', '5.8', '2.2', 'Iris-virginica']
['7.6', '3', '6.6', '2.1', 'Iris-virginica']
['4.9', '2.5', '4.5', '1.7', 'Iris-virginica']
['7.3', '2.9', '6.3', '1.8', 'Iris-virginica']
['6.7', '2.5', '5.8', '1.8', 'Iris-virginica']
['7.2', '3.6', '6.1', '2.5', 'Iris-virginica']
['6.5', '3.2', '5.1', '2', 'Iris-virginica']
['6.4', '2.7', '5.3', '1.9', 'Iris-virginica']
['6.8', '3', '5.5', '2.1', 'Iris-virginica']
['5.7', '2.5', '5', '2', 'Iris-virginica']
['5.8', '2.8', '5.1', '2.4', 'Iris-virginica']
['6.4', '3.2', '5.3', '2.3', 'Iris-virginica']
['6.5', '3', '5.5', '1.8', 'Iris-virginica']
['7.7', '3.8', '6.7', '2.2', 'Iris-virginica']
['7.7', '2.6', '6.9', '2.3', 'Iris-virginica']
['6', '2.2', '5', '1.5', 'Iris-virginica']
['6.9', '3.2', '5.7', '2.3', 'Iris-virginica']
['5.6', '2.8', '4.9', '2', 'Iris-virginica']
['7.7', '2.8', '6.7', '2', 'Iris-virginica']
['6.3', '2.7', '4.9', '1.8', 'Iris-virginica']
['6.7', '3.3', '5.7', '2.1', 'Iris-virginica']
['7.2', '3.2', '6', '1.8', 'Iris-virginica']
['6.2', '2.8', '4.8', '1.8', 'Iris-virginica']
['6.1', '3', '4.9', '1.8', 'Iris-virginica']
['6.4', '2.8', '5.6', '2.1', 'Iris-virginica']
['7.2', '3', '5.8', '1.6', 'Iris-virginica']
['7.4', '2.8', '6.1', '1.9', 'Iris-virginica']
['7.9', '3.8', '6.4', '2', 'Iris-virginica']
['6.4', '2.8', '5.6', '2.2', 'Iris-virginica']
['6.3', '2.8', '5.1', '1.5', 'Iris-virginica']
['6.1', '2.6', '5.6', '1.4', 'Iris-virginica']
['7.7', '3', '6.1', '2.3', 'Iris-virginica']
['6.3', '3.4', '5.6', '2.4', 'Iris-virginica']
['6.4', '3.1', '5.5', '1.8', 'Iris-virginica']
['6', '3', '4.8', '1.8', 'Iris-virginica']
['6.9', '3.1', '5.4', '2.1', 'Iris-virginica']
['6.7', '3.1', '5.6', '2.4', 'Iris-virginica']
['6.9', '3.1', '5.1', '2.3', 'Iris-virginica']
['5.8', '2.7', '5.1', '1.9', 'Iris-virginica']
['6.8', '3.2', '5.9', '2.3', 'Iris-virginica']
['6.7', '3.3', '5.7', '2.5', 'Iris-virginica']
['6.7', '3', '5.2', '2.3', 'Iris-virginica']
['6.3', '2.5', '5', '1.9', 'Iris-virginica']
['6.5', '3', '5.2', '2', 'Iris-virginica']
['6.2', '3.4', '5.4', '2.3', 'Iris-virginica']
['5.9', '3', '5.1', '1.8', 'Iris-virginica']

In [4]:
#With open takes 2 arguments file locations and name, r os for read, w is for write.

In [5]:
  # delimiter=”,” -> which means it needs to also know how to separate the values

# 2.Using readlines():
                The readlines() method in Python reads all lines from a text file and returns them as a list,
                each line is an item in the list.
                less efficient for large files because it loads the entire file into memory.

In [6]:
with open("./iris.csv", "r") as csvfile:
    first_line = csvfile.readline()
    print(first_line)

sepal_length,sepal_width,petal_length,petal_width,species

In [7]:
#READLINES() - To read multiple lines.

In [8]:
with open("./iris.csv", "r") as csvfile:
    all_lines = csvfile.readlines()
    print(all_lines)

['sepal_length,sepal_width,petal_length,petal_width,species\n', '5.1,3.5,1.4,0.2,Iris-setosa\n', '4.9,3,1.4,0.2,Iris-setosa\n', '4.7,3.2,1.3,0.2,Iris-setosa\n', '4.6,3.1,1.5,0.2,Iris-setosa\n', '5,3.6,1.4,0.2,Iris-setosa\n', '5.4,3.9,1.7,0.4,Iris-setosa\n', '4.6,3.4,1.4,0.3,Iris-setosa\n', '5,3.4,1.5,0.2,Iris-setosa\n', '4.4,2.9,1.4,0.2,Iris-setosa\n', '4.9,3.1,1.5,0.1,Iris-setosa\n', '5.4,3.7,1.5,0.2,Iris-setosa\n', '4.8,3.4,1.6,0.2,Iris-setosa\n', '4.8,3,1.4,0.1,Iris-setosa\n', '4.3,3,1.1,0.1,Iris-setosa\n', '5.8,4,1.2,0.2,Iris-setosa\n', '5.7,4.4,1.5,0.4,Iris-setosa\n', '5.4,3.9,1.3,0.4,Iris-setosa\n', '5.1,3.5,1.4,0.3,Iris-setosa\n', '5.7,3.8,1.7,0.3,Iris-setosa\n', '5.1,3.8,1.5,0.3,Iris-setosa\n', '5.4,3.4,1.7,0.2,Iris-setosa\n', '5.1,3.7,1.5,0.4,Iris-setosa\n', '4.6,3.6,1,0.2,Iris-setosa\n', '5.1,3.3,1.7,0.5,Iris-setosa\n', '4.8,3.4,1.9,0.2,Iris-setosa\n', '5,3,1.6,0.2,Iris-setosa\n', '5,3.4,1.6,0.4,Iris-setosa\n', '5.2,3.5,1.5,0.2,Iris-setosa\n', '5.2,3.4,1.4,0.2,Iris-setosa\n', '4.7,3.2,1.6,0.2,Iris-setosa\n', '4.8,3.1,1.6,0.2,Iris-setosa\n', '5.4,3.4,1.5,0.4,Iris-setosa\n', '5.2,4.1,1.5,0.1,Iris-setosa\n', '5.5,4.2,1.4,0.2,Iris-setosa\n', '4.9,3.1,1.5,0.1,Iris-setosa\n', '5,3.2,1.2,0.2,Iris-setosa\n', '5.5,3.5,1.3,0.2,Iris-setosa\n', '4.9,3.1,1.5,0.1,Iris-setosa\n', '4.4,3,1.3,0.2,Iris-setosa\n', '5.1,3.4,1.5,0.2,Iris-setosa\n', '5,3.5,1.3,0.3,Iris-setosa\n', '4.5,2.3,1.3,0.3,Iris-setosa\n', '4.4,3.2,1.3,0.2,Iris-setosa\n', '5,3.5,1.6,0.6,Iris-setosa\n', '5.1,3.8,1.9,0.4,Iris-setosa\n', '4.8,3,1.4,0.3,Iris-setosa\n', '5.1,3.8,1.6,0.2,Iris-setosa\n', '4.6,3.2,1.4,0.2,Iris-setosa\n', '5.3,3.7,1.5,0.2,Iris-setosa\n', '5,3.3,1.4,0.2,Iris-setosa\n', '7,3.2,4.7,1.4,Iris-versicolor\n', '6.4,3.2,4.5,1.5,Iris-versicolor\n', '6.9,3.1,4.9,1.5,Iris-versicolor\n', '5.5,2.3,4,1.3,Iris-versicolor\n', '6.5,2.8,4.6,1.5,Iris-versicolor\n', '5.7,2.8,4.5,1.3,Iris-versicolor\n', '6.3,3.3,4.7,1.6,Iris-versicolor\n', '4.9,2.4,3.3,1,Iris-versicolor\n', '6.6,2.9,4.6,1.3,Iris-versicolor\n', '5.2,2.7,3.9,1.4,Iris-versicolor\n', '5,2,3.5,1,Iris-versicolor\n', '5.9,3,4.2,1.5,Iris-versicolor\n', '6,2.2,4,1,Iris-versicolor\n', '6.1,2.9,4.7,1.4,Iris-versicolor\n', '5.6,2.9,3.6,1.3,Iris-versicolor\n', '6.7,3.1,4.4,1.4,Iris-versicolor\n', '5.6,3,4.5,1.5,Iris-versicolor\n', '5.8,2.7,4.1,1,Iris-versicolor\n', '6.2,2.2,4.5,1.5,Iris-versicolor\n', '5.6,2.5,3.9,1.1,Iris-versicolor\n', '5.9,3.2,4.8,1.8,Iris-versicolor\n', '6.1,2.8,4,1.3,Iris-versicolor\n', '6.3,2.5,4.9,1.5,Iris-versicolor\n', '6.1,2.8,4.7,1.2,Iris-versicolor\n', '6.4,2.9,4.3,1.3,Iris-versicolor\n', '6.6,3,4.4,1.4,Iris-versicolor\n', '6.8,2.8,4.8,1.4,Iris-versicolor\n', '6.7,3,5,1.7,Iris-versicolor\n', '6,2.9,4.5,1.5,Iris-versicolor\n', '5.7,2.6,3.5,1,Iris-versicolor\n', '5.5,2.4,3.8,1.1,Iris-versicolor\n', '5.5,2.4,3.7,1,Iris-versicolor\n', '5.8,2.7,3.9,1.2,Iris-versicolor\n', '6,2.7,5.1,1.6,Iris-versicolor\n', '5.4,3,4.5,1.5,Iris-versicolor\n', '6,3.4,4.5,1.6,Iris-versicolor\n', '6.7,3.1,4.7,1.5,Iris-versicolor\n', '6.3,2.3,4.4,1.3,Iris-versicolor\n', '5.6,3,4.1,1.3,Iris-versicolor\n', '5.5,2.5,4,1.3,Iris-versicolor\n', '5.5,2.6,4.4,1.2,Iris-versicolor\n', '6.1,3,4.6,1.4,Iris-versicolor\n', '5.8,2.6,4,1.2,Iris-versicolor\n', '5,2.3,3.3,1,Iris-versicolor\n', '5.6,2.7,4.2,1.3,Iris-versicolor\n', '5.7,3,4.2,1.2,Iris-versicolor\n', '5.7,2.9,4.2,1.3,Iris-versicolor\n', '6.2,2.9,4.3,1.3,Iris-versicolor\n', '5.1,2.5,3,1.1,Iris-versicolor\n', '5.7,2.8,4.1,1.3,Iris-versicolor\n', '6.3,3.3,6,2.5,Iris-virginica\n', '5.8,2.7,5.1,1.9,Iris-virginica\n', '7.1,3,5.9,2.1,Iris-virginica\n', '6.3,2.9,5.6,1.8,Iris-virginica\n', '6.5,3,5.8,2.2,Iris-virginica\n', '7.6,3,6.6,2.1,Iris-virginica\n', '4.9,2.5,4.5,1.7,Iris-virginica\n', '7.3,2.9,6.3,1.8,Iris-virginica\n', '6.7,2.5,5.8,1.8,Iris-virginica\n', '7.2,3.6,6.1,2.5,Iris-virginica\n', '6.5,3.2,5.1,2,Iris-virginica\n', '6.4,2.7,5.3,1.9,Iris-virginica\n', '6.8,3,5.5,2.1,Iris-virginica\n', '5.7,2.5,5,2,Iris-virginica\n', '5.8,2.8,5.1,2.4,Iris-virginica\n', '6.4,3.2,5.3,2.3,Iris-virginica\n', '6.5,3,5.5,1.8,Iris-virginica\n', '7.7,3.8,6.7,2.2,Iris-virginica\n', '7.7,2.6,6.9,2.3,Iris-virginica\n', '6,2.2,5,1.5,Iris-virginica\n', '6.9,3.2,5.7,2.3,Iris-virginica\n', '5.6,2.8,4.9,2,Iris-virginica\n', '7.7,2.8,6.7,2,Iris-virginica\n', '6.3,2.7,4.9,1.8,Iris-virginica\n', '6.7,3.3,5.7,2.1,Iris-virginica\n', '7.2,3.2,6,1.8,Iris-virginica\n', '6.2,2.8,4.8,1.8,Iris-virginica\n', '6.1,3,4.9,1.8,Iris-virginica\n', '6.4,2.8,5.6,2.1,Iris-virginica\n', '7.2,3,5.8,1.6,Iris-virginica\n', '7.4,2.8,6.1,1.9,Iris-virginica\n', '7.9,3.8,6.4,2,Iris-virginica\n', '6.4,2.8,5.6,2.2,Iris-virginica\n', '6.3,2.8,5.1,1.5,Iris-virginica\n', '6.1,2.6,5.6,1.4,Iris-virginica\n', '7.7,3,6.1,2.3,Iris-virginica\n', '6.3,3.4,5.6,2.4,Iris-virginica\n', '6.4,3.1,5.5,1.8,Iris-virginica\n', '6,3,4.8,1.8,Iris-virginica\n', '6.9,3.1,5.4,2.1,Iris-virginica\n', '6.7,3.1,5.6,2.4,Iris-virginica\n', '6.9,3.1,5.1,2.3,Iris-virginica\n', '5.8,2.7,5.1,1.9,Iris-virginica\n', '6.8,3.2,5.9,2.3,Iris-virginica\n', '6.7,3.3,5.7,2.5,Iris-virginica\n', '6.7,3,5.2,2.3,Iris-virginica\n', '6.3,2.5,5,1.9,Iris-virginica\n', '6.5,3,5.2,2,Iris-virginica\n', '6.2,3.4,5.4,2.3,Iris-virginica\n', '5.9,3,5.1,1.8,Iris-virginica\n']

In [9]:
#This prints out a raw output with everything in the csvfile

# 3.Using Pandas:
            1.powerful library for data manipulation and analysis
            2.This method is recommended for most scenarios due to its flexibility and ease of use

In [17]:
import pandas as pd

In [18]:
iris=pd.read_csv('iris.csv')

In [61]:
iris.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

# 4.Read CSV file in python using csv.DictReader:
                1.each row is represented as a dictionary with column names as keys.
                2.Useful when you want to access columns by name.

In [23]:
with open('iris.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
       print(row)

{'sepal_length': '5.1', 'sepal_width': '3.5', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.9', 'sepal_width': '3', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.7', 'sepal_width': '3.2', 'petal_length': '1.3', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.6', 'sepal_width': '3.1', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5', 'sepal_width': '3.6', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5.4', 'sepal_width': '3.9', 'petal_length': '1.7', 'petal_width': '0.4', 'species': 'Iris-setosa'}
{'sepal_length': '4.6', 'sepal_width': '3.4', 'petal_length': '1.4', 'petal_width': '0.3', 'species': 'Iris-setosa'}
{'sepal_length': '5', 'sepal_width': '3.4', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.4', 'sepal_width': '2.9', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.9', 'sepal_width': '3.1', 'petal_length': '1.5', 'petal_width': '0.1', 'species': 'Iris-setosa'}
{'sepal_length': '5.4', 'sepal_width': '3.7', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.8', 'sepal_width': '3.4', 'petal_length': '1.6', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.8', 'sepal_width': '3', 'petal_length': '1.4', 'petal_width': '0.1', 'species': 'Iris-setosa'}
{'sepal_length': '4.3', 'sepal_width': '3', 'petal_length': '1.1', 'petal_width': '0.1', 'species': 'Iris-setosa'}
{'sepal_length': '5.8', 'sepal_width': '4', 'petal_length': '1.2', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5.7', 'sepal_width': '4.4', 'petal_length': '1.5', 'petal_width': '0.4', 'species': 'Iris-setosa'}
{'sepal_length': '5.4', 'sepal_width': '3.9', 'petal_length': '1.3', 'petal_width': '0.4', 'species': 'Iris-setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.5', 'petal_length': '1.4', 'petal_width': '0.3', 'species': 'Iris-setosa'}
{'sepal_length': '5.7', 'sepal_width': '3.8', 'petal_length': '1.7', 'petal_width': '0.3', 'species': 'Iris-setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.8', 'petal_length': '1.5', 'petal_width': '0.3', 'species': 'Iris-setosa'}
{'sepal_length': '5.4', 'sepal_width': '3.4', 'petal_length': '1.7', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.7', 'petal_length': '1.5', 'petal_width': '0.4', 'species': 'Iris-setosa'}
{'sepal_length': '4.6', 'sepal_width': '3.6', 'petal_length': '1', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.3', 'petal_length': '1.7', 'petal_width': '0.5', 'species': 'Iris-setosa'}
{'sepal_length': '4.8', 'sepal_width': '3.4', 'petal_length': '1.9', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5', 'sepal_width': '3', 'petal_length': '1.6', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5', 'sepal_width': '3.4', 'petal_length': '1.6', 'petal_width': '0.4', 'species': 'Iris-setosa'}
{'sepal_length': '5.2', 'sepal_width': '3.5', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5.2', 'sepal_width': '3.4', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.7', 'sepal_width': '3.2', 'petal_length': '1.6', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.8', 'sepal_width': '3.1', 'petal_length': '1.6', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5.4', 'sepal_width': '3.4', 'petal_length': '1.5', 'petal_width': '0.4', 'species': 'Iris-setosa'}
{'sepal_length': '5.2', 'sepal_width': '4.1', 'petal_length': '1.5', 'petal_width': '0.1', 'species': 'Iris-setosa'}
{'sepal_length': '5.5', 'sepal_width': '4.2', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.9', 'sepal_width': '3.1', 'petal_length': '1.5', 'petal_width': '0.1', 'species': 'Iris-setosa'}
{'sepal_length': '5', 'sepal_width': '3.2', 'petal_length': '1.2', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5.5', 'sepal_width': '3.5', 'petal_length': '1.3', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.9', 'sepal_width': '3.1', 'petal_length': '1.5', 'petal_width': '0.1', 'species': 'Iris-setosa'}
{'sepal_length': '4.4', 'sepal_width': '3', 'petal_length': '1.3', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.4', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5', 'sepal_width': '3.5', 'petal_length': '1.3', 'petal_width': '0.3', 'species': 'Iris-setosa'}
{'sepal_length': '4.5', 'sepal_width': '2.3', 'petal_length': '1.3', 'petal_width': '0.3', 'species': 'Iris-setosa'}
{'sepal_length': '4.4', 'sepal_width': '3.2', 'petal_length': '1.3', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5', 'sepal_width': '3.5', 'petal_length': '1.6', 'petal_width': '0.6', 'species': 'Iris-setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.8', 'petal_length': '1.9', 'petal_width': '0.4', 'species': 'Iris-setosa'}
{'sepal_length': '4.8', 'sepal_width': '3', 'petal_length': '1.4', 'petal_width': '0.3', 'species': 'Iris-setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.8', 'petal_length': '1.6', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '4.6', 'sepal_width': '3.2', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5.3', 'sepal_width': '3.7', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '5', 'sepal_width': '3.3', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'Iris-setosa'}
{'sepal_length': '7', 'sepal_width': '3.2', 'petal_length': '4.7', 'petal_width': '1.4', 'species': 'Iris-versicolor'}
{'sepal_length': '6.4', 'sepal_width': '3.2', 'petal_length': '4.5', 'petal_width': '1.5', 'species': 'Iris-versicolor'}
{'sepal_length': '6.9', 'sepal_width': '3.1', 'petal_length': '4.9', 'petal_width': '1.5', 'species': 'Iris-versicolor'}
{'sepal_length': '5.5', 'sepal_width': '2.3', 'petal_length': '4', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '6.5', 'sepal_width': '2.8', 'petal_length': '4.6', 'petal_width': '1.5', 'species': 'Iris-versicolor'}
{'sepal_length': '5.7', 'sepal_width': '2.8', 'petal_length': '4.5', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '6.3', 'sepal_width': '3.3', 'petal_length': '4.7', 'petal_width': '1.6', 'species': 'Iris-versicolor'}
{'sepal_length': '4.9', 'sepal_width': '2.4', 'petal_length': '3.3', 'petal_width': '1', 'species': 'Iris-versicolor'}
{'sepal_length': '6.6', 'sepal_width': '2.9', 'petal_length': '4.6', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '5.2', 'sepal_width': '2.7', 'petal_length': '3.9', 'petal_width': '1.4', 'species': 'Iris-versicolor'}
{'sepal_length': '5', 'sepal_width': '2', 'petal_length': '3.5', 'petal_width': '1', 'species': 'Iris-versicolor'}
{'sepal_length': '5.9', 'sepal_width': '3', 'petal_length': '4.2', 'petal_width': '1.5', 'species': 'Iris-versicolor'}
{'sepal_length': '6', 'sepal_width': '2.2', 'petal_length': '4', 'petal_width': '1', 'species': 'Iris-versicolor'}
{'sepal_length': '6.1', 'sepal_width': '2.9', 'petal_length': '4.7', 'petal_width': '1.4', 'species': 'Iris-versicolor'}
{'sepal_length': '5.6', 'sepal_width': '2.9', 'petal_length': '3.6', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '6.7', 'sepal_width': '3.1', 'petal_length': '4.4', 'petal_width': '1.4', 'species': 'Iris-versicolor'}
{'sepal_length': '5.6', 'sepal_width': '3', 'petal_length': '4.5', 'petal_width': '1.5', 'species': 'Iris-versicolor'}
{'sepal_length': '5.8', 'sepal_width': '2.7', 'petal_length': '4.1', 'petal_width': '1', 'species': 'Iris-versicolor'}
{'sepal_length': '6.2', 'sepal_width': '2.2', 'petal_length': '4.5', 'petal_width': '1.5', 'species': 'Iris-versicolor'}
{'sepal_length': '5.6', 'sepal_width': '2.5', 'petal_length': '3.9', 'petal_width': '1.1', 'species': 'Iris-versicolor'}
{'sepal_length': '5.9', 'sepal_width': '3.2', 'petal_length': '4.8', 'petal_width': '1.8', 'species': 'Iris-versicolor'}
{'sepal_length': '6.1', 'sepal_width': '2.8', 'petal_length': '4', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '6.3', 'sepal_width': '2.5', 'petal_length': '4.9', 'petal_width': '1.5', 'species': 'Iris-versicolor'}
{'sepal_length': '6.1', 'sepal_width': '2.8', 'petal_length': '4.7', 'petal_width': '1.2', 'species': 'Iris-versicolor'}
{'sepal_length': '6.4', 'sepal_width': '2.9', 'petal_length': '4.3', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '6.6', 'sepal_width': '3', 'petal_length': '4.4', 'petal_width': '1.4', 'species': 'Iris-versicolor'}
{'sepal_length': '6.8', 'sepal_width': '2.8', 'petal_length': '4.8', 'petal_width': '1.4', 'species': 'Iris-versicolor'}
{'sepal_length': '6.7', 'sepal_width': '3', 'petal_length': '5', 'petal_width': '1.7', 'species': 'Iris-versicolor'}
{'sepal_length': '6', 'sepal_width': '2.9', 'petal_length': '4.5', 'petal_width': '1.5', 'species': 'Iris-versicolor'}
{'sepal_length': '5.7', 'sepal_width': '2.6', 'petal_length': '3.5', 'petal_width': '1', 'species': 'Iris-versicolor'}
{'sepal_length': '5.5', 'sepal_width': '2.4', 'petal_length': '3.8', 'petal_width': '1.1', 'species': 'Iris-versicolor'}
{'sepal_length': '5.5', 'sepal_width': '2.4', 'petal_length': '3.7', 'petal_width': '1', 'species': 'Iris-versicolor'}
{'sepal_length': '5.8', 'sepal_width': '2.7', 'petal_length': '3.9', 'petal_width': '1.2', 'species': 'Iris-versicolor'}
{'sepal_length': '6', 'sepal_width': '2.7', 'petal_length': '5.1', 'petal_width': '1.6', 'species': 'Iris-versicolor'}
{'sepal_length': '5.4', 'sepal_width': '3', 'petal_length': '4.5', 'petal_width': '1.5', 'species': 'Iris-versicolor'}
{'sepal_length': '6', 'sepal_width': '3.4', 'petal_length': '4.5', 'petal_width': '1.6', 'species': 'Iris-versicolor'}
{'sepal_length': '6.7', 'sepal_width': '3.1', 'petal_length': '4.7', 'petal_width': '1.5', 'species': 'Iris-versicolor'}
{'sepal_length': '6.3', 'sepal_width': '2.3', 'petal_length': '4.4', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '5.6', 'sepal_width': '3', 'petal_length': '4.1', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '5.5', 'sepal_width': '2.5', 'petal_length': '4', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '5.5', 'sepal_width': '2.6', 'petal_length': '4.4', 'petal_width': '1.2', 'species': 'Iris-versicolor'}
{'sepal_length': '6.1', 'sepal_width': '3', 'petal_length': '4.6', 'petal_width': '1.4', 'species': 'Iris-versicolor'}
{'sepal_length': '5.8', 'sepal_width': '2.6', 'petal_length': '4', 'petal_width': '1.2', 'species': 'Iris-versicolor'}
{'sepal_length': '5', 'sepal_width': '2.3', 'petal_length': '3.3', 'petal_width': '1', 'species': 'Iris-versicolor'}
{'sepal_length': '5.6', 'sepal_width': '2.7', 'petal_length': '4.2', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '5.7', 'sepal_width': '3', 'petal_length': '4.2', 'petal_width': '1.2', 'species': 'Iris-versicolor'}
{'sepal_length': '5.7', 'sepal_width': '2.9', 'petal_length': '4.2', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '6.2', 'sepal_width': '2.9', 'petal_length': '4.3', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '5.1', 'sepal_width': '2.5', 'petal_length': '3', 'petal_width': '1.1', 'species': 'Iris-versicolor'}
{'sepal_length': '5.7', 'sepal_width': '2.8', 'petal_length': '4.1', 'petal_width': '1.3', 'species': 'Iris-versicolor'}
{'sepal_length': '6.3', 'sepal_width': '3.3', 'petal_length': '6', 'petal_width': '2.5', 'species': 'Iris-virginica'}
{'sepal_length': '5.8', 'sepal_width': '2.7', 'petal_length': '5.1', 'petal_width': '1.9', 'species': 'Iris-virginica'}
{'sepal_length': '7.1', 'sepal_width': '3', 'petal_length': '5.9', 'petal_width': '2.1', 'species': 'Iris-virginica'}
{'sepal_length': '6.3', 'sepal_width': '2.9', 'petal_length': '5.6', 'petal_width': '1.8', 'species': 'Iris-virginica'}
{'sepal_length': '6.5', 'sepal_width': '3', 'petal_length': '5.8', 'petal_width': '2.2', 'species': 'Iris-virginica'}
{'sepal_length': '7.6', 'sepal_width': '3', 'petal_length': '6.6', 'petal_width': '2.1', 'species': 'Iris-virginica'}
{'sepal_length': '4.9', 'sepal_width': '2.5', 'petal_length': '4.5', 'petal_width': '1.7', 'species': 'Iris-virginica'}
{'sepal_length': '7.3', 'sepal_width': '2.9', 'petal_length': '6.3', 'petal_width': '1.8', 'species': 'Iris-virginica'}
{'sepal_length': '6.7', 'sepal_width': '2.5', 'petal_length': '5.8', 'petal_width': '1.8', 'species': 'Iris-virginica'}
{'sepal_length': '7.2', 'sepal_width': '3.6', 'petal_length': '6.1', 'petal_width': '2.5', 'species': 'Iris-virginica'}
{'sepal_length': '6.5', 'sepal_width': '3.2', 'petal_length': '5.1', 'petal_width': '2', 'species': 'Iris-virginica'}
{'sepal_length': '6.4', 'sepal_width': '2.7', 'petal_length': '5.3', 'petal_width': '1.9', 'species': 'Iris-virginica'}
{'sepal_length': '6.8', 'sepal_width': '3', 'petal_length': '5.5', 'petal_width': '2.1', 'species': 'Iris-virginica'}
{'sepal_length': '5.7', 'sepal_width': '2.5', 'petal_length': '5', 'petal_width': '2', 'species': 'Iris-virginica'}
{'sepal_length': '5.8', 'sepal_width': '2.8', 'petal_length': '5.1', 'petal_width': '2.4', 'species': 'Iris-virginica'}
{'sepal_length': '6.4', 'sepal_width': '3.2', 'petal_length': '5.3', 'petal_width': '2.3', 'species': 'Iris-virginica'}
{'sepal_length': '6.5', 'sepal_width': '3', 'petal_length': '5.5', 'petal_width': '1.8', 'species': 'Iris-virginica'}
{'sepal_length': '7.7', 'sepal_width': '3.8', 'petal_length': '6.7', 'petal_width': '2.2', 'species': 'Iris-virginica'}
{'sepal_length': '7.7', 'sepal_width': '2.6', 'petal_length': '6.9', 'petal_width': '2.3', 'species': 'Iris-virginica'}
{'sepal_length': '6', 'sepal_width': '2.2', 'petal_length': '5', 'petal_width': '1.5', 'species': 'Iris-virginica'}
{'sepal_length': '6.9', 'sepal_width': '3.2', 'petal_length': '5.7', 'petal_width': '2.3', 'species': 'Iris-virginica'}
{'sepal_length': '5.6', 'sepal_width': '2.8', 'petal_length': '4.9', 'petal_width': '2', 'species': 'Iris-virginica'}
{'sepal_length': '7.7', 'sepal_width': '2.8', 'petal_length': '6.7', 'petal_width': '2', 'species': 'Iris-virginica'}
{'sepal_length': '6.3', 'sepal_width': '2.7', 'petal_length': '4.9', 'petal_width': '1.8', 'species': 'Iris-virginica'}
{'sepal_length': '6.7', 'sepal_width': '3.3', 'petal_length': '5.7', 'petal_width': '2.1', 'species': 'Iris-virginica'}
{'sepal_length': '7.2', 'sepal_width': '3.2', 'petal_length': '6', 'petal_width': '1.8', 'species': 'Iris-virginica'}
{'sepal_length': '6.2', 'sepal_width': '2.8', 'petal_length': '4.8', 'petal_width': '1.8', 'species': 'Iris-virginica'}
{'sepal_length': '6.1', 'sepal_width': '3', 'petal_length': '4.9', 'petal_width': '1.8', 'species': 'Iris-virginica'}
{'sepal_length': '6.4', 'sepal_width': '2.8', 'petal_length': '5.6', 'petal_width': '2.1', 'species': 'Iris-virginica'}
{'sepal_length': '7.2', 'sepal_width': '3', 'petal_length': '5.8', 'petal_width': '1.6', 'species': 'Iris-virginica'}
{'sepal_length': '7.4', 'sepal_width': '2.8', 'petal_length': '6.1', 'petal_width': '1.9', 'species': 'Iris-virginica'}
{'sepal_length': '7.9', 'sepal_width': '3.8', 'petal_length': '6.4', 'petal_width': '2', 'species': 'Iris-virginica'}
{'sepal_length': '6.4', 'sepal_width': '2.8', 'petal_length': '5.6', 'petal_width': '2.2', 'species': 'Iris-virginica'}
{'sepal_length': '6.3', 'sepal_width': '2.8', 'petal_length': '5.1', 'petal_width': '1.5', 'species': 'Iris-virginica'}
{'sepal_length': '6.1', 'sepal_width': '2.6', 'petal_length': '5.6', 'petal_width': '1.4', 'species': 'Iris-virginica'}
{'sepal_length': '7.7', 'sepal_width': '3', 'petal_length': '6.1', 'petal_width': '2.3', 'species': 'Iris-virginica'}
{'sepal_length': '6.3', 'sepal_width': '3.4', 'petal_length': '5.6', 'petal_width': '2.4', 'species': 'Iris-virginica'}
{'sepal_length': '6.4', 'sepal_width': '3.1', 'petal_length': '5.5', 'petal_width': '1.8', 'species': 'Iris-virginica'}
{'sepal_length': '6', 'sepal_width': '3', 'petal_length': '4.8', 'petal_width': '1.8', 'species': 'Iris-virginica'}
{'sepal_length': '6.9', 'sepal_width': '3.1', 'petal_length': '5.4', 'petal_width': '2.1', 'species': 'Iris-virginica'}
{'sepal_length': '6.7', 'sepal_width': '3.1', 'petal_length': '5.6', 'petal_width': '2.4', 'species': 'Iris-virginica'}
{'sepal_length': '6.9', 'sepal_width': '3.1', 'petal_length': '5.1', 'petal_width': '2.3', 'species': 'Iris-virginica'}
{'sepal_length': '5.8', 'sepal_width': '2.7', 'petal_length': '5.1', 'petal_width': '1.9', 'species': 'Iris-virginica'}
{'sepal_length': '6.8', 'sepal_width': '3.2', 'petal_length': '5.9', 'petal_width': '2.3', 'species': 'Iris-virginica'}
{'sepal_length': '6.7', 'sepal_width': '3.3', 'petal_length': '5.7', 'petal_width': '2.5', 'species': 'Iris-virginica'}
{'sepal_length': '6.7', 'sepal_width': '3', 'petal_length': '5.2', 'petal_width': '2.3', 'species': 'Iris-virginica'}
{'sepal_length': '6.3', 'sepal_width': '2.5', 'petal_length': '5', 'petal_width': '1.9', 'species': 'Iris-virginica'}
{'sepal_length': '6.5', 'sepal_width': '3', 'petal_length': '5.2', 'petal_width': '2', 'species': 'Iris-virginica'}
{'sepal_length': '6.2', 'sepal_width': '3.4', 'petal_length': '5.4', 'petal_width': '2.3', 'species': 'Iris-virginica'}
{'sepal_length': '5.9', 'sepal_width': '3', 'petal_length': '5.1', 'petal_width': '1.8', 'species': 'Iris-virginica'}

# List of Methods to Write a CSV file in python
    1. Write CSV file using csv.writer
    2. Write CSV file using writelines() function
    3. Write CSV file using Pandas
    4. Write CSV file using csv.DictWriter

In [51]:
#1.Using csv.writer
import csv

In [26]:
header = ['Name', 'M1 Score', 'M2 Score']
data = [['Alex', 62, 80], ['Bard', 45, 56], ['Joe', 85, 98]]

In [27]:
filename = 'Students_Data.csv'
with open(filename, 'w', newline="") as file:
    csvwriter = csv.writer(file) # 2. create a csvwriter object
    csvwriter.writerow(header) # 4. write the header
    csvwriter.writerows(data) # 5. write the rest of the data

In [52]:
#Trying to read the file that is written
with open("Students_Data.csv", "r") as csvfile:
    reader_variable = csv.reader(csvfile, delimiter=",")
    for row in reader_variable:
        print(row)

['Name', 'M1 Score', 'M2 Score']
['Alex', '62', '80']
['Brad', '45', '56']
['Joey', '85', '98']

# Using .writelines()
            writelines() iterates through each list, 
            converts the list elements to a string, 
            and then writes it to the csv file.

In [63]:
header = 'Name,M1 Score,M2 Score'
data = [['Alex', 62, 80], ['Brad', 45, 56], ['Joey', 85, 98]]
filename = 'Student_scores.csv'

with open(filename, 'w') as file:
    file.write(header + '\n')  # Write the header
    for row in data:
        file.write(','.join(map(str, row)) + '\n')

# Using pandas:
        1. Written in the form of dataframes
        2. Dataframes -> organizes data into 2D tablemof rows and columns

In [65]:

header = ['Name', 'M1 Score', 'M2 Score']
data = [['Alex', 62, 80], ['Brad', 45, 56], ['Joey', 85, 98]]

In [66]:
df = pd.DataFrame(data, columns=header)

In [67]:
df

   Name  M1 Score  M2 Score
0  Alex        62        80
1  Brad        45        56
2  Joey        85        98

In [68]:
df.to_csv('Stud_data.csv', index=True)

# using csv.DictWriter

In [48]:
import csv

In [50]:

with open('Students_Data.csv', 'w', newline='') as csvfile:
    data = [
        {'Name': 'Alex', 'M1 Score': 62, 'M2 Score': 80},
        {'Name': 'Brad', 'M1 Score': 45, 'M2 Score': 56},
        {'Name': 'Joey', 'M1 Score': 85, 'M2 Score': 98}
    ]
    fieldnames = ['Name', 'M1 Score', 'M2 Score']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(data)

In [55]:
#df.to_json("output_data.json")

# Read a json file

# 1.Using json.load():
                function reads a JSON file and returns its content as a Python dictionary

In [56]:
import json

with open('output_data.json', 'r') as file:
    data = json.load(file)
    print(data)

{'Name': {'0': 'Alex', '1': 'Brad', '2': 'Joey'}, 'M1 Score': {'0': 62, '1': 45, '2': 85}, 'M2 Score': {'0': 80, '1': 56, '2': 98}}

# 2. Using Pandas:
            1. When we need tabular format

In [58]:
import pandas as pd

df = pd.read_json('output_data.json')
print(df.head())

   Name  M1 Score  M2 Score
0  Alex        62        80
1  Brad        45        56
2  Joey        85        98

# Reding Excel files:

In [69]:
import pandas as pd
df = pd.read_excel('employee_data.xlsx')
print(df)

    EmployeeID  FirstName    LastName                         Email  \
0        29254      David     Barrera            pellis@example.net
1        41781     Taylor     Jenkins       staceydavis@example.org
2        64042      James   Mccormick       carrdouglas@example.com
3        32251     Bailey  Fitzgerald        smithamber@example.net
4        36809      Jacob     Ramirez          angela24@example.com
5        51888      James   Rodriguez          joshua25@example.com
6         9943       Lisa      Barker      bradfigueroa@example.org
7        49845      Amber    Thompson     christopher15@example.net
8         5254      Bruce      Thomas           frank92@example.com
9         5746     Jeremy    Castillo      thompsonalex@example.com
10        8234      Ricky     Johnson    jenniferrogers@example.org
11       11533     Thomas     Pearson       andreahuber@example.org
12       77498      Kevin    Thornton     goodwinedward@example.com
13       22518      Tanya        Berg          justin04@example.org
14       94888      Wendy         Cox         rfigueroa@example.net
15       95613    Heather   Henderson           fbaxter@example.com
16       79688      Linda      Hudson          adrian53@example.com
17       35809  Dominique      Moreno    andersonandrea@example.com
18       12876       Erin      Morgan      heatherochoa@example.com
19       83055    Jocelyn     Stewart              plee@example.org
20       33604       Omar     Acevedo   franklinwilliam@example.org
21       77720      Danny       Lopez        patricia15@example.net
22       65132    Rebecca    Thompson           vsavage@example.com
23       76118     Adrian      Fisher      griffinkelly@example.com
24       57174     Carlos     Stewart          nicole15@example.org
25        2009    Jeffrey     Parsons           lmurphy@example.net
26       41164     Jeremy     Rosario       rogerscarly@example.net
27       50621   Jennifer      Martin          kjohnson@example.org
28        6571    Matthew       Banks      joshualawson@example.com
29       84799    Melissa        Chen   michaelferguson@example.org
30        5498    Michael     Mueller            xpetty@example.com
31       96317     Sandra      Waters        terribates@example.org
32        1495      Laura      Becker           paula46@example.org
33       12071      Gregg      Hughes             ksims@example.org
34        5032    Yolanda      George          wjohnson@example.com
35       32243     Steven       Miles      stewartshawn@example.org
36       95078   Kimberly     Barrett  clementsjennifer@example.com
37       72795    William       Smith           oporter@example.net
38       75165      Devin       Lewis             rmann@example.net
39       95371    William       Bauer             fchen@example.com

                               JobTitle  \
0                   Information officer
1       Administrator, local government
2    Surveyor, planning and development
3             Medical technical officer
4                         Hotel manager
5                 Accountant, chartered
6                 Glass blower/designer
7                Recruitment consultant
8                       Psychotherapist
9                            Ergonomist
10        Engineer, civil (contracting)
11              Scientist, audiological
12                 Journalist, magazine
13                   Wellsite geologist
14                Journalist, newspaper
15  Exhibitions officer, museum/gallery
16                       Futures trader
17            Engineer, technical sales
18                            Dietitian
19        Speech and language therapist
20                       Phytotherapist
21                      Physiotherapist
22      Administrator, local government
23    Environmental health practitioner
24                     Public librarian
25                     Engineer, energy
26                Management consultant
27                          Firefighter
28                 Engineer, production
29           Horticulturist, commercial
30                   Veterinary surgeon
31                        Haematologist
32                       Dramatherapist
33                 Chartered accountant
34                   Restaurant manager
35                   Press photographer
36                            Herbalist
37          Civil Service fast streamer
38            Health and safety adviser
39                      Producer, radio

                                   Department             Manager  \
0            matrix revolutionary convergence       Richard Brown
1                    iterate magnetic systems    Lindsay Crawford
2                  e-enable end-to-end niches       Willie Curtis
3                   monetize killer e-markets       Pamela Taylor
4             envisioneer user-centric models           Mark Dyer
5                  evolve visionary solutions       Melissa Lewis
6              envisioneer innovative metrics       Brian Herrera
7                integrate dynamic interfaces        Lauren Smith
8                  scale front-end e-services       Ruth Townsend
9                e-enable wireless e-services          Eric Jones
10          enhance plug-and-play communities          Mark Sloan
11                   leverage dynamic schemas      Kristina Smith
12         transition extensible deliverables           Lisa Reed
13  disintermediate web-enabled supply-chains      Angela Anthony
14              streamline enterprise vortals         Laura Welch
15                enable compelling solutions     Kelly Miller MD
16                         target rich niches       Jamie Ramirez
17             deliver enterprise experiences        Sandra Reyes
18             integrate one-to-one e-markets  Phillip Watkins MD
19                             engage B2C ROI       Shane Aguirre
20            orchestrate value-added portals      Ashley Morales
21                  engage virtual e-commerce      Michael Murray
22           generate next-generation portals      Robert Jimenez
23               optimize killer action-items        Debbie Burns
24              monetize seamless convergence     Michael Barnett
25          engineer interactive deliverables      Timothy Holmes
26                      target wireless users        Brian Newman
27       re-intermediate enterprise bandwidth    Michael Alvarado
28               incentivize sticky mindshare       Deanna Decker
29             deliver cross-platform systems        Brandon Gray
30           cultivate open-source e-business        Eileen Burke
31         embrace ubiquitous infrastructures   Elizabeth Jackson
32                  syndicate rich e-commerce       Robert Fowler
33       cultivate cutting-edge relationships    Adrienne Griffin
34          aggregate cross-media communities        Jason Cooper
35     re-contextualize collaborative vortals    Tamara Patel DDS
36             deliver vertical supply-chains         James Duran
37            brand world-class supply-chains   Amanda Montgomery
38                   deploy extensible models        Krystal Mays
39                 engineer enterprise models        Ivan Brennan

         HireDate    Salary              Location  Experience  DateOfJoining  \
0   1634601600000  66652.25             Perryland           2  1634601600000
1   1645142400000  66948.36              Johnview           2  1645142400000
2   1631318400000  72428.14            Martinview           2  1631318400000
3   1677888000000  43359.32   South Elizabethtown           0  1677888000000
4   1643155200000  35195.14           Alvarezland           2  1643155200000
5   1674864000000  78075.05             New Kevin           1  1674864000000
6   1606435200000  39699.56              Lopezton           3  1606435200000
7   1561852800000  34905.53              Ginafort           4  1561852800000
8   1606435200000  64946.53        North Adamtown           3  1606435200000
9   1585872000000  68253.00       Thompsonchester           3  1585872000000
10  1668124800000  55993.38            North Paul           1  1668124800000
11  1614816000000  75171.01             Pughhaven           2  1614816000000
12  1558224000000  53703.95        Mcconnellburgh           4  1558224000000
13  1651104000000  75097.24         North Vanessa           1  1651104000000
14  1603670400000  49117.94           Yangchester           3  1603670400000
15  1705536000000  51515.54       New Sandramouth           0  1705536000000
16  1573257600000  79480.39           Joshuamouth           4  1573257600000
17  1580169600000  69455.12         North Michael           4  1580169600000
18  1586044800000  43701.84  Lake Christopherport           3  1586044800000
19  1578787200000  30525.24    North Brandonshire           4  1578787200000
20  1649894400000  48341.12             Jamesland           1  1649894400000
21  1641686400000  75156.12            Ingramside           2  1641686400000
22  1628035200000  79686.68          Lake Valerie           2  1628035200000
23  1682467200000  43005.32             Peterfort           0  1682467200000
24  1601856000000  48755.90             Laurafurt           3  1601856000000
25  1605052800000  34500.85      Christineborough           3  1605052800000
26  1569715200000  59364.40           Wrightville           4  1569715200000
27  1669680000000  37462.35         South Matthew           1  1669680000000
28  1559606400000  36692.63           Walkermouth           4  1559606400000
29  1690761600000  68625.01          Kristinmouth           0  1690761600000
30  1684022400000  70927.40      South Amychester           0  1684022400000
31  1695600000000  37628.73          Adrienneport           0  1695600000000
32  1581292800000  39043.54          West Brandon           4  1581292800000
33  1638662400000  66633.59             Hullburgh           2  1638662400000
34  1665014400000  78002.76            Morristown           1  1665014400000
35  1552953600000  52895.53            Soniaville           4  1552953600000
36  1600819200000  35285.90             Jasonport           3  1600819200000
37  1617235200000  47587.49          North Robert           2  1617235200000
38  1657411200000  32971.60         East Evanbury           1  1657411200000
39  1672358400000  48746.28           Deborahside           1  1672358400000

                   City           State                               Country
0      New Samanthafort    Rhode Island                         French Guiana
1   North Kimberlyhaven      New Jersey                               Namibia
2          Heathermouth     Mississippi                              Bulgaria
3            Wrightside      New Jersey                       Kyrgyz Republic
4     East Rachaelville    South Dakota                      French Polynesia
5            Lake Tyler          Oregon                                  Iran
6        Lake Jackburgh        Colorado                                 Qatar
7        Stephanieshire       Tennessee                Bosnia and Herzegovina
8        Mclaughlinview   West Virginia                                Uganda
9           New Anthony      Washington                            Guadeloupe
10          Wrightshire        Oklahoma  United States Minor Outlying Islands
11       New Garrettton        Oklahoma                                  Mali
12           Torresstad        Missouri                            Tajikistan
13           North Lisa      New Mexico                               Iceland
14            Jerryside      Washington                            Tajikistan
15            Paulburgh          Nevada                                Turkey
16           Samuelbury   West Virginia                      Christmas Island
17            Port Kyle         Wyoming                                  Mali
18       South Cristian  North Carolina                               Liberia
19          New Matthew       Louisiana           French Southern Territories
20      Lake Damonburgh         Arizona                      Marshall Islands
21     North Loganburgh  North Carolina           French Southern Territories
22         Matthewsstad    North Dakota                               Reunion
23           Hannahtown         Arizona                               Morocco
24           Lake Tammy      California                          Sierra Leone
25          Cynthiatown    North Dakota                              Djibouti
26          East Angela        Missouri                                 Malta
27          Kaitlynstad         Arizona                         Liechtenstein
28     Lake Miguelmouth         Indiana                                Rwanda
29            Whiteview         Alabama                  Netherlands Antilles
30         Jacksonburgh     Mississippi                         Liechtenstein
31         Lake Michael         Vermont                            Mauritania
32           Laurenbury     Mississippi                              Tanzania
33            Clarkstad      New Jersey                         Guinea-Bissau
34        West Maryfort      New Mexico                               Bermuda
35              Royside        New York                               Nigeria
36         Jacksonhaven           Texas                               Somalia
37            Whitestad      New Jersey                  Netherlands Antilles
38       Matthewborough       Louisiana                               Tunisia
39              Timview        Michigan                      French Polynesia

In [71]:
df.head()

,EmployeeID,FirstName,LastName,Email,JobTitle,Department,Manager,HireDate,Salary,Location,Experience,DateOfJoining,City,State,Country
0,29254,David,Barrera,pellis@example.net,Information officer,matrix revolutionary convergence,Richard Brown,1634601600000,66652.25,Perryland,2,1634601600000,New Samanthafort,Rhode Island,French Guiana
1,41781,Taylor,Jenkins,staceydavis@example.org,"Administrator, local government",iterate magnetic systems,Lindsay Crawford,1645142400000,66948.36,Johnview,2,1645142400000,North Kimberlyhaven,New Jersey,Namibia
2,64042,James,Mccormick,carrdouglas@example.com,"Surveyor, planning and development",e-enable end-to-end niches,Willie Curtis,1631318400000,72428.14,Martinview,2,1631318400000,Heathermouth,Mississippi,Bulgaria
3,32251,Bailey,Fitzgerald,smithamber@example.net,Medical technical officer,monetize killer e-markets,Pamela Taylor,1677888000000,43359.32,South Elizabethtown,0,1677888000000,Wrightside,New Jersey,Kyrgyz Republic
4,36809,Jacob,Ramirez,angela24@example.com,Hotel manager,envisioneer user-centric models,Mark Dyer,1643155200000,35195.14,Alvarezland,2,1643155200000,East Rachaelville,South Dakota,French Polynesia